### ISSUE TITLE
Grind for Low R Signatures

### ISSUE THREAD

**Issue by SeedSigner** [diybitcoinhardware/embit#12]
(a related issue was raised in the SeedSigner repo: https://github.com/SeedSigner/seedsigner/issues/32)

Requesting that Embit add support for grinding for low R signatures to resolve compatibility issues SeedSigner is experiencing related to fee estimation.

**Comment by stepansnigirev** [comment]
Makes sense, will do.

**Comment by SeedSigner** [comment]
Thank you for looking at this so quickly!
