### ISSUE TITLE
PSBT change vs receiving address example

### ISSUE THREAD

**Issue by newtonick** [diybitcoinhardware/embit#18]
Is there a way to tell if an output in a psbt is a change or receiving address? I'm basically asking for an example of how to use embit psbt to see if an output (or multiple outputs) are specifically going to a change addresses. You have a good example on how to tell if an output is change, but It seems as if it does not different between change to a change address vs receiving address.

Based on your examples, this is my understanding of how to check if a native segwit multisig psbt transaction output is going to back to the sending wallet.

```
# For this example I'll just going to assume the psbt script type is p2wsh
tx = psbt.PSBT.parse(base64_psbt)

# looping over all outputs to check if the out is change
for i, out in enumerate(tx.outputs):
	is_out_same_as_in_wallet = False
	sc = script.p2wsh(out.witness_script)
	if sc.data == tx.tx.vout[i].script_pubkey.data:
            is_out_same_as_in_wallet = True
```

The only partial solution I can figure out to accomplish this is by dumping change addresses from hdkey and comparing them to `tx.tx.vout[i].script_pubkey.address(NETWORKS["test"])` (as an example). There must be a better way. I'm hoping you can maybe add this to your change.py example.

dumping change addresses from hdkey:
```
change_addr_list = []
for i in range(100):
    pub = xpub.derive("m/1/%d" % i).key
    sc = script.p2wpkh(pub) #native segwit (not sure this would even work for multisig ...)
    change_addr_list.append(sc.address(NETWORKS["test"]))
```

Thanks!

**Comment by stepansnigirev** [comment]
The easiest is to check if the second to last bip32 derivation index is 1.

I'll look into the change example in the next few days, maybe I can refactor it using descriptors - then it will be easier to detect if it's a change or receiving address.
Descriptors already have a method to check if PSBT scope belongs to them or not, so using that can make the code cleaner.
