### ISSUE TITLE
RIPEMD160 missing in Openssl3

### ISSUE THREAD

**Issue by relativisticelectron** [diybitcoinhardware/embit#28]
Openssl was upgraded to [3.0.2](https://packages.ubuntu.com/jammy/openssl) in ubuntu 22.04.

Problem: RIPEMD160 was deactivated in Openssl3 https://github.com/openssl/openssl/issues/16994     and embit uses openssl for this in https://github.com/diybitcoinhardware/embit/blob/977d144fe2809f9135ad443167517f1a167df500/src/embit/hashes.py#L12

This problem  has been discussed on hwi: https://github.com/bitcoin-core/HWI/issues/305
Possible solution through a Python-only implementation:   Bitcoin test framework: https://github.com/bitcoin/bitcoin/commit/68ca8677e039a60b9f51938987d784cb58a3c995

**Comment by stepansnigirev** [comment]
Fixed via https://github.com/diybitcoinhardware/embit/commit/2e293b000d20562327151c72a4aed672d0a944bc
