### ISSUE TITLE
Native Segwit MultiSig Generation Mismatch

### ISSUE THREAD

**Issue by yunier2002** [diybitcoinhardware/embit#51]
Hey guys, not sure if this is an issue or not but don't know where else to post this question/issue. 

I'm using this example from this link to generate the first native multisig (P2WSH) address for a test wallet I'm using, but the address that this embit code produces is different than what I get from other software like Sparrow/Specter/BlueWallet, not sure if I'm doing anything wrong or if there's something else missing from that example, or if it's a bug.

I replaced the top part of example for single sig since not interested in that. And replaced with code to generate the encoded key from the actual seeds to verify those keys are correct as those are what I'm entering in the multisig example. And also the seeds and xpubs to test address generation in other software for comparison.

Other software generates address: bc1qufmytewrnhqw0cwq0mt5uhtfz9kp67xpmyclx8w50mt4zx80cjssjzahah
Emibt example generates address: bc1qfuvauxhhz0vhyrszg3nlqj7up59d70sj3uqe92t6xddct58xm5lqlpm2nl

If anyone can help in identifying the discrepancy I'll appreciate it

https://github.com/diybitcoinhardware/embit/blob/master/examples/addresses.py

Attaching pythong code in txt file

[MultiSigExample.txt](https://github.com/diybitcoinhardware/embit/files/12877109/MultiSigExample.txt)

**Comment by jdlcdl** [comment]
Have you checked out embit.Descriptor and the example [here](https://github.com/diybitcoinhardware/embit/blob/master/examples/descriptor.py)?

**Comment by yunier2002** [comment]
Thanks for pointing me to that example @jdlcdl . I had tried the Descriptor module before but wasn't working either with my generated descriptor string, was getting same bad address. Tried that example and it's working correctly now using the "classic descriptor" one which adds "/0/*" at the end of the pubkeys. That was the difference. 

I also tried before the full descriptor string from Sparrow which uses the paired descriptor example with "/<0;1>/*" at the end and that always failed and also it's failing in that example without changing anything, so it could be a bug in the code. I'll close this now that I figure out how I can get the correct address.

My example and error below:

Traceback (most recent call last):
  File "C:/Bitcoin/Test.py", line 54, in <module>
    main()
  File "C:/Bitcoin/Test.py", line 42, in main
    desc = Descriptor.from_string(dstr)
  File "C:\Bitcoin\venv\lib\site-packages\embit\descriptor\descriptor.py", line 253, in from_string
    res = cls.read_from(s)
  File "C:\Bitcoin\venv\lib\site-packages\embit\descriptor\descriptor.py", line 298, in read_from
    miniscript = Miniscript.read_from(s)
  File "C:\Bitcoin\venv\lib\site-packages\embit\descriptor\miniscript.py", line 71, in read_from
    args = MiniscriptCls.read_arguments(s)
  File "C:\Bitcoin\venv\lib\site-packages\embit\descriptor\miniscript.py", line 92, in read_arguments
    args.append(nextcls.read_from(s))
  File "C:\Bitcoin\venv\lib\site-packages\embit\descriptor\arguments.py", line 228, in read_from
    der.decode(), allow_hardened=allow_hardened
  File "C:\Bitcoin\venv\lib\site-packages\embit\descriptor\arguments.py", line 110, in from_string
    cls.parse_element(d, allow_hardened, allow_set) for d in der.split("/")
  File "C:\Bitcoin\venv\lib\site-packages\embit\descriptor\arguments.py", line 110, in <listcomp>
    cls.parse_element(d, allow_hardened, allow_set) for d in der.split("/")
  File "C:\Bitcoin\venv\lib\site-packages\embit\descriptor\arguments.py", line 133, in parse_element
    i = int(d)
ValueError: invalid literal for int() with base 10: '<0;1>'

[MultiSigDescriptorError.txt](https://github.com/diybitcoinhardware/embit/files/12887664/MultiSigDescriptorError.txt)
