### ISSUE TITLE
libsecp256k1 system library

### ISSUE THREAD

**Issue by ZeroPointEnergy** [diybitcoinhardware/embit#9]
In an effort to package this library to eventually be able to package newer versions of specter-desktop I stumbled over the following issue.

Since I have to remove every bundled library and build everything from source I had the issue that the libsecp256k1 library wasn't detected. This could be fixed with the following patch:
```
--- a/src/embit/util/ctypes_secp256k1.py
+++ b/src/embit/util/ctypes_secp256k1.py
@@ -45,7 +45,7 @@ def _find_library():
         return path
     # try searching
     if not library_path:
-        library_path = ctypes.util.find_library("libsecp256k1")
+        library_path = ctypes.util.find_library("secp256k1")
     # library search failed
     if not library_path:
         if platform.system() == "Linux" and os.path.isfile(
```
python example:
```
>>> print(ctypes.util.find_library("libsecp256k1"))
None
>>> print(ctypes.util.find_library("secp256k1"))
libsecp256k1.so.0
```
This is on Gentoo Linux, so I'm not sure if this is a bug in the python code or something distribution specific. I didn't do any further tests with other operating systems yet.

However, when running the tests I get the following error:
```
AttributeError: /usr/lib64/libsecp256k1.so.0: undefined symbol: secp256k1_pedersen_commitment_parse
```

When I grep the latest version of the upstream libsecp256k1 project (https://github.com/bitcoin-core/secp256k1) I don't find any such function. Is there a specific fork of the libsecp256k1 library required for this to work?

**Comment by stepansnigirev** [comment]
It's using libsecp256k1-zkp as we started integrating Liquid into Specter.
I added your patch in https://github.com/diybitcoinhardware/embit/commit/9780103f18586901adccf9dedb2bafce50e098a9.
Also in master if liquid stuff is missing in libsecp256k1 it should not break bitcoin functionality of the library.
Can you test with master branch of embit?

**Comment by ZeroPointEnergy** [comment]
It finds the lib with the master branch, thanks for the quick fix. Will look in how I can package the forked lib, thanks for the info.

**Comment by stepansnigirev** [comment]
It should work with secp256k1-zkp configured with the following flags:
```
./configure --enable-module-ecdh --enable-module-musig --enable-module-recovery --enable-module-generator --enable-module-rangeproof --enable-module-schnorrsig --enable-module-surjectionproof --enable-experimental
```
